" indent: command not found
" the call to :runtime you can find below.  If you wish to change any of those
" settings, you should do it in this file (/etc/vim/vimrc), since debian.vim
" will be overwritten everytime an upgrade of the vim packages is performed.
" It is recommended to make changes after sourcing debian.vim since it alters
" the value of the 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
"syntax on

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
"if has("autocmd")
"  filetype plugin indent on
"endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden		" Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

" XDG Settings
" https://www.reddit.com/r/vim/comments/uc0n06/comment/i68jecj/

if has('unix')
    silent !mkdir $XDG_CACHE_HOME/vim/{swapfiles,backup} -p > /dev/null 2>&1
    set directory=$XDG_CACHE_HOME/vim/swapfiles//
    set backupdir=$XDG_CACHE_HOME/vim/backup//
    set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
    set packpath=$XDG_CONFIG_HOME/vim/
    set runtimepath^=$XDG_CONFIG_HOME/vim
    set runtimepath+=$XDG_CONFIG_HOME/vim/after,
                \$XDG_CONFIG_HOME/vim/ftplugin,
                \$XDG_CONFIG_HOME/vim/spell/
    let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"
endif

set hlsearch                        "高亮度反白
set backspace=2                     "可隨時用倒退鍵刪除
set ruler                           "可顯示最後一列的狀態
set showmode                        "左下角那一列的狀態
set number                          "顯示行號
set mouse=nvi                       "使用滑鼠

filetype on                         "檔案類型檢測
filetype plugin on                  "根據檔案類型加載插件

syntax enable                       "打開語法高亮
syntax on                           "自動語法高亮
"set bg=dark                         "顯示不同的底色色調
colorscheme catppuccin_mocha        "語法高亮主題
set cursorline                      "突出顯示當前 Row
"set cursorcolumn                    "突出顯示當前 Column

set ignorecase smartcase            "搜尋時忽略大小寫，但在有一個或以上大寫字母時仍保持對大小寫敏感
set incsearch                       "輸入搜尋內容時就顯示搜尋結果

set autoindent                      "自動縮排
set smartindent                     "換行時智能縮進
set expandtab                       "空格代替 Tab
set tabstop=4                       "Tab 長度爲4
set softtabstop=4                   "Backspace 一次可以刪除4個空格
set nowrap                          "禁止自動換行
set encoding=utf8                   "編碼 UTF-8

set autochdir                       "自動切換當前目錄
